// Interface strings (chrome only). Course content never lives here.
const strings = {
  en: {
    contents: 'Contents',
    chapter: 'Chapter',
    search: 'Search',
    searchPlaceholder: 'Search the reference…',
    searchHint: 'Type to search titles and text',
    noResults: 'No matches',
    close: 'Close',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    switchLang: 'العربية',
    switchLangLabel: 'Switch to Arabic',
    theme: 'Toggle theme',
    light: 'Light',
    dark: 'Dark',
    previous: 'Previous',
    next: 'Next',
    printAll: 'Print the whole reference',
    printView: 'Print view',
    printViewNote: 'Every chapter, in order. Use your browser’s Print command to save a PDF.',
    backToReference: 'Back to the reference',
    placeholder: 'Image placeholder',
    expectedFile: 'Expected file',
    tip: 'Tip',
    warning: 'Warning',
    quote: 'Quote',
    note: 'Added for this course',
    linkToSection: 'Link to this section',
    onThisPage: 'On this page',
    keyboardHint: 'Navigate',
    keyboardSelect: 'Open',
    keyboardClose: 'Close',
    inChapter: 'in',
    landing: 'Landing Stage',
    signIn: 'Sign in',
    logIn: 'Log in',
    signUp: 'Sign up',
    logInTitle: 'Welcome back',
    logInSubtitle: 'Enter your credentials to access your account',
    signUpTitle: 'Create an account',
    signUpSubtitle: 'Join thousands of designers mastering interfaces',
    email: 'Email address',
    emailPlaceholder: 'name@example.com',
    password: 'Password',
    passwordPlaceholder: '••••••••',
    fullName: 'Full name',
    fullNamePlaceholder: 'Tom Smith',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    nextStep: 'Next step',
    orContinueWith: 'Or continue with',
    continueWithApple: 'Apple',
    continueWithGoogle: 'Google',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    agreeTerms: 'I agree to the Terms and Privacy Policy',
    fixedGridBadge: 'Fixed Grid Architecture',
    fixedGridLabel: 'Fixed Grid (Standard)',
    fluidGridLabel: 'Fluid Grid (Anti-pattern)',
    toggleGridLines: '12-Col Grid',
    fixedGridDemoNote: 'On a fixed grid, the form maintains a sensible 420px width while extra screen space becomes margins.',
    fluidGridDemoNote: 'On a fluid grid, stretching edge-to-edge pushes labels metres away from inputs and destroys readability.',
    backToPlatform: 'Back to Reference',
  },
  ar: {
    contents: 'المحتويات',
    chapter: 'فصل',
    search: 'بحث',
    searchPlaceholder: 'ابحث في المرجع…',
    searchHint: 'اكتب للبحث في العناوين والنصوص',
    noResults: 'لا توجد نتائج',
    close: 'إغلاق',
    openMenu: 'فتح القائمة',
    closeMenu: 'إغلاق القائمة',
    switchLang: 'English',
    switchLangLabel: 'التبديل إلى الإنجليزية',
    theme: 'تبديل السمة',
    light: 'فاتح',
    dark: 'داكن',
    previous: 'السابق',
    next: 'التالي',
    printAll: 'طباعة المرجع كاملًا',
    printView: 'نسخة الطباعة',
    printViewNote: 'كل الفصول بالترتيب. استخدم أمر الطباعة في المتصفح لحفظ ملف PDF.',
    backToReference: 'العودة إلى المرجع',
    placeholder: 'صورة مؤقتة',
    expectedFile: 'الملف المتوقع',
    tip: 'نصيحة',
    warning: 'تنبيه',
    quote: 'اقتباس',
    note: 'إضافة خاصة بالكورس',
    linkToSection: 'رابط هذا القسم',
    onThisPage: 'في هذه الصفحة',
    keyboardHint: 'تنقّل',
    keyboardSelect: 'فتح',
    keyboardClose: 'إغلاق',
    inChapter: 'في',
    landing: 'صفحة البداية',
    signIn: 'تسجيل الدخول',
    logIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    logInTitle: 'مرحبًا بك مجددًا',
    logInSubtitle: 'أدخل بيانات اعتمادك للوصول إلى حسابك',
    signUpTitle: 'إنشاء حساب جديد',
    signUpSubtitle: 'انضم لآلاف المصممين المتقنين لهندسة الواجهات',
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'name@example.com',
    password: 'كلمة المرور',
    passwordPlaceholder: '••••••••',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'أحمد محمد',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    nextStep: 'الخطوة التالية',
    orContinueWith: 'أو المتابعة عبر',
    continueWithApple: 'Apple',
    continueWithGoogle: 'Google',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    agreeTerms: 'أوافق على الشروط وسياسة الخصوصية',
    fixedGridBadge: 'بنية الجريد الثابت',
    fixedGridLabel: 'جريد ثابت (القياسي)',
    fluidGridLabel: 'جريد مرن (خطأ شائع)',
    toggleGridLines: 'جريد 12 عمود',
    fixedGridDemoNote: 'على الجريد الثابت، يحافظ الفورم على عرض متوازن (420px) وتتحول مساحة الشاشة الإضافية لهوامش مريحة.',
    fluidGridDemoNote: 'على الجريد المرن، يؤدي تمديد الفورم عبر الشاشة إلى إبعاد الليبل أمتارًا عن الحقل ويدمر القراءة.',
    backToPlatform: 'العودة للمرجع',
  },
}

export function t(lang, key) {
  return strings[lang]?.[key] ?? strings.en[key] ?? key
}
