// Interface strings (chrome only). Course content never lives here.
const strings = {
  en: {
    contents: 'Contents',
    chapter: 'Chapter',
    search: 'Search',
    searchPlaceholder: 'Search the reference…',
    searchHint: 'Type to search titles and text',
    noResults: 'No matches',
    close: 'Close',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    switchLang: 'العربية',
    switchLangLabel: 'Switch to Arabic',
    theme: 'Toggle theme',
    light: 'Light',
    dark: 'Dark',
    previous: 'Previous',
    next: 'Next',
    printAll: 'Print the whole reference',
    printView: 'Print view',
    printViewNote: 'Every chapter, in order. Use your browser’s Print command to save a PDF.',
    backToReference: 'Back to the reference',
    placeholder: 'Image placeholder',
    expectedFile: 'Expected file',
    tip: 'Tip',
    warning: 'Warning',
    quote: 'Quote',
    note: 'Added for this course',
    linkToSection: 'Link to this section',
    onThisPage: 'On this page',
    keyboardHint: 'Navigate',
    keyboardSelect: 'Open',
    keyboardClose: 'Close',
    inChapter: 'in',
    listenChapter: 'Listen to chapter',
    listenSection: 'Listen to section',
    pause: 'Pause',
    resume: 'Resume',
    playbackSpeed: 'Playback speed',
    nextSection: 'Next section',
    prevSection: 'Previous section',
    closePlayer: 'Close audio player',
    nowReading: 'Now reading',
    listeningToChapter: 'Reading chapter',
    ttsServiceUnavailable: 'Speech synthesis is unavailable in this browser.',
  },
  ar: {
    contents: 'المحتويات',
    chapter: 'فصل',
    search: 'بحث',
    searchPlaceholder: 'ابحث في المرجع…',
    searchHint: 'اكتب للبحث في العناوين والنصوص',
    noResults: 'لا توجد نتائج',
    close: 'إغلاق',
    openMenu: 'فتح القائمة',
    closeMenu: 'إغلاق القائمة',
    switchLang: 'English',
    switchLangLabel: 'التبديل إلى الإنجليزية',
    theme: 'تبديل السمة',
    light: 'فاتح',
    dark: 'داكن',
    previous: 'السابق',
    next: 'التالي',
    printAll: 'طباعة المرجع كاملًا',
    printView: 'نسخة الطباعة',
    printViewNote: 'كل الفصول بالترتيب. استخدم أمر الطباعة في المتصفح لحفظ ملف PDF.',
    backToReference: 'العودة إلى المرجع',
    placeholder: 'صورة مؤقتة',
    expectedFile: 'الملف المتوقع',
    tip: 'نصيحة',
    warning: 'تنبيه',
    quote: 'اقتباس',
    note: 'إضافة خاصة بالكورس',
    linkToSection: 'رابط هذا القسم',
    onThisPage: 'في هذه الصفحة',
    keyboardHint: 'تنقّل',
    keyboardSelect: 'فتح',
    keyboardClose: 'إغلاق',
    inChapter: 'في',
    listenChapter: 'استمع إلى الفصل',
    listenSection: 'استمع إلى هذا القسم',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    playbackSpeed: 'سرعة القراءة',
    nextSection: 'القسم التالي',
    prevSection: 'القسم السابق',
    closePlayer: 'إغلاق مشغل الصوت',
    nowReading: 'قراءة الآن',
    listeningToChapter: 'قراءة الفصل',
    ttsServiceUnavailable: 'محرك تحويل النص إلى صوت غير متاح في هذا المتصفح.',
  },
}

export function t(lang, key) {
  return strings[lang]?.[key] ?? strings.en[key] ?? key
}
