/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    // 4px base grid spacing matching DESIGN_SYSTEM.md §1 & §8
    spacing: {
      0: '0',
      px: '1px',
      0.5: '2px',
      1: '4px',
      1.5: '6px',
      2: '8px',
      2.5: '10px',
      3: '12px',
      3.5: '14px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      14: '56px',
      16: '64px',
      18: '72px',
      20: '80px',
      22: '88px',
      24: '96px',
      28: '112px',
      32: '128px',
      36: '144px',
      40: '160px',
      48: '192px',
      56: '224px',
      64: '256px',
      70: '280px',
      80: '320px',
      'space-1': 'var(--space-1)',
      'space-2': 'var(--space-2)',
      'space-3': 'var(--space-3)',
      'space-4': 'var(--space-4)',
      'space-5': 'var(--space-5)',
      'space-6': 'var(--space-6)',
    },
    // Type scale matching DESIGN_SYSTEM.md §1 & §3
    fontSize: {
      label: ['11px', { lineHeight: '1.40', letterSpacing: '0.14em' }],
      xs: ['12px', { lineHeight: '16px' }],
      sm: ['14px', { lineHeight: '1.55' }],
      small: ['14px', { lineHeight: '1.55' }],
      base: ['17px', { lineHeight: '1.65' }],
      body: ['17px', { lineHeight: '1.65' }],
      lg: ['20px', { lineHeight: '28px' }],
      h3: ['22px', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
      xl: ['24px', { lineHeight: '30px' }],
      '2xl': ['28px', { lineHeight: '34px' }],
      h2: ['34px', { lineHeight: '1.10', letterSpacing: '-0.02em' }],
      '3xl': ['34px', { lineHeight: '1.10', letterSpacing: '-0.02em' }],
      '4xl': ['42px', { lineHeight: '46px' }],
      display: ['56px', { lineHeight: '1.02', letterSpacing: '-0.03em' }],
    },
    fontFamily: {
      sans: ['Cairo', '"Public Sans"', 'Helvetica', 'Arial', 'sans-serif'],
      arabic: ['Cairo', '"Public Sans"', 'Helvetica', 'Arial', 'sans-serif'],
      cairo: ['Cairo', 'sans-serif'],
      'ibm-plex': ['"IBM Plex Sans Arabic"', 'sans-serif'],
      mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#FFFFFF',
      black: '#1A1A17',
      // Design system tokens (§1)
      action: 'var(--color-action)',
      'action-hover': 'var(--color-action-hover)',
      'action-pressed': 'var(--color-action-pressed)',
      'action-tint': 'var(--color-action-tint)',
      'action-tint-line': 'var(--color-action-tint-line)',
      ground: 'var(--color-ground)',
      'surface-sunken': 'var(--color-surface-sunken)',
      body: 'var(--color-body)',
      muted: 'var(--color-muted)',
      'line-hover': 'var(--color-line-hover)',
      warning: 'var(--color-warning)',
      'warning-tint': 'var(--color-warning-tint)',
      'warning-line': 'var(--color-warning-line)',
      error: 'var(--color-error)',
      'error-hover': 'var(--color-error-hover)',

      // Opacity-compatible channels for neutrals and brand
      bg: 'rgb(var(--c-bg) / <alpha-value>)',
      surface: 'rgb(var(--c-surface) / <alpha-value>)',
      raised: 'rgb(var(--c-raised) / <alpha-value>)',
      line: 'rgb(var(--c-line) / <alpha-value>)',
      'line-strong': 'rgb(var(--c-line-strong) / <alpha-value>)',
      ink: 'rgb(var(--c-ink) / <alpha-value>)',
      'ink-2': 'rgb(var(--c-ink-2) / <alpha-value>)',
      'ink-3': 'rgb(var(--c-ink-3) / <alpha-value>)',
      accent: 'rgb(var(--c-accent) / <alpha-value>)',
      'accent-ink': 'rgb(var(--c-accent-ink) / <alpha-value>)',
      'accent-soft': 'rgb(var(--c-accent-soft) / <alpha-value>)',
      warn: 'rgb(var(--c-warn) / <alpha-value>)',
      'warn-soft': 'rgb(var(--c-warn-soft) / <alpha-value>)',
      note: 'rgb(var(--c-note) / <alpha-value>)',
      'note-soft': 'rgb(var(--c-note-soft) / <alpha-value>)',
      success: 'rgb(var(--c-success) / <alpha-value>)',
      'success-soft': 'rgb(var(--c-success-soft) / <alpha-value>)',
    },
    borderRadius: {
      none: '0',
      tag: 'var(--radius-tag)', // 6px
      control: 'var(--radius-control)', // 8px
      card: 'var(--radius-card)', // 12px
      pill: 'var(--radius-pill)', // 999px
      sm: '4px',
      DEFAULT: '8px',
      md: '10px',
      lg: '12px',
      xl: '16px',
      '2xl': '24px',
      full: '999px',
    },
    extend: {
      boxShadow: {
        raised: 'var(--shadow-raised)',
        overlay: 'var(--shadow-overlay)',
        glass: '0 8px 32px 0 rgba(0, 0, 0, 0.08)',
        'glass-dark': '0 8px 32px 0 rgba(0, 0, 0, 0.35)',
        glow: '0 0 16px -2px var(--color-action-tint)',
      },
      maxWidth: {
        prose: '70ch', // §3 Measure caps at 70 characters
      },
      transitionTimingFunction: {
        out: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
      },
    },
  },
  plugins: [],
}
